<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/ru/tl_downloadarchiv.php 
 * 
 * Contao extension: downloadarchive 1.0.0 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Dmitri Kuznetsov (kuzmich), http://www.onfreedom.ru 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiv']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['title']['1'] = "Введите название архива загрузок. Оно будет отображаться, только в панели управления.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['showMeta']['0'] = "Показать мета-данные";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['showMeta']['1'] = "Хотите показать дату загрузки и размер файла для каждой записи?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadDirectory']['0'] = "Читать папки";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadDirectory']['1'] = "Вы можете добавить все файлы внутри выбранной папки. Это работает, только если файлы, не подключены к этому архиву загрузок.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadSubdir']['0'] = "Сканировать подпапки";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadSubdir']['1'] = "Вы хотите сканировать подпапки?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['dirSRC']['0'] = "Выберите папку";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['dirSRC']['1'] = "Выберите папку, которую хотите просканировать.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['prefix']['0'] = "Использовать префикс имени";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['prefix']['1'] = "Вы можете включить автоматическую генерацию названий для каждого элемента, используя числа в префиксе строки (напр: \"Наша продукция 0001\").";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['extension']['0'] = "Расширения";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['extension']['1'] = "Вы можете ограничить сканируемые файлы, указав расширения. Пожалуйста, введите через запятую список расширений, которые вы хотите добавить.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['publishAll']['0'] = "Автопубликация всех файлов";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['publishAll']['1'] = "Отметьте эту опцию, для опубликации всех файлов при импорте папки.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['class']['0'] = "CSS класс";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['class']['1'] = "Вы можете добавить CSS класс архиву. Этот класс будет назначен каждому файлу.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['deleteConfirm'] = "Вы действительно хотите удалить архив загрузок ID%?\n(Файлы не будут удалены с сервера!)";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['new']['0'] = "Новый архив";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['new']['1'] = "Создать новый архив загрузок.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['edit']['0'] = "Редактировать архив";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['edit']['1'] = "Редактировать архив ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['copy']['0'] = "Копировать архив";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['copy']['1'] = "Копировать архив ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['delete']['0'] = "Удалить архив";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['delete']['1'] = "Удалить архив ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['show']['0'] = "Показать детали";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['show']['1'] = "Показать детали архива с ID %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['title_legend'] = "Название";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['directory_legend'] = "Читать папку";
 
?>
