<?php
/**
 * TL_ROOT/system/modules/downloadarchive/languages/fr/tl_downloadarchiv.php 
 * 
 * TYPOlight extension: downloadarchive 0.5.1 stable 
 * French translation file 
 * 
 * Copyright : &copy; 2008 Felix Pfeiffer - Neue Medien 
 * License   : LGPL 
 * Author    : Felix Pfeiffer (felixpfeiffer), http://www.felixpfeiffer.de 
 * Translator: Guéric Folliot (gueric), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchiv']['title']['0'] = "Nom";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['title']['1'] = "Entrez un nom pour l'archive à télécharger. Ce nom n'apparaîtra que dans le back-office.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['showMeta']['0'] = "Afficher les données meta?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['showMeta']['1'] = "Voulez vous afficher la date d'envoi et la taille de fichier pour chaque élément?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadDirectory']['0'] = "Lire un dossier?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadDirectory']['1'] = "Vous pouvez ajouter tous les fichiers à l'intérieur d'un dossier choisi. Ceci marche seulement s'il n'y a aucun fichier connecté à l'archive à télécharger.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadSubdir']['0'] = "Parcourir les sous-dossiers";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['loadSubdir']['1'] = "Voulez vous parcourir tous les sous-dossiers?";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['dirSRC']['0'] = "Sélectionner un dossier";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['dirSRC']['1'] = "Sélectionnez le dossier que vous voulez parcourir.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['prefix']['0'] = "Utiliser un préfixe";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['prefix']['1'] = "Vous pouvez générer automatiquement le titre pour chaque élément à télécharger en utilisant ce préfixe et un nombre incrémenté(Ex: \"Notre Produit 0001\").";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['extension']['0'] = "Extensions";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['extension']['1'] = "Vous pouvez limiter l'examen à certaines extensions de fichier. Veuillez entrer une liste d'extensions, séparées par des virgules, que vous voulez ajouter.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['deleteConfirm'] = "Etes vous sûr(e) de vouloir supprimer l'archive à télécharger ID%?\n(Les fichiers NE SERONT PAS supprimer du serveur)";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['new']['0'] = "Nouvelle archive";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['new']['1'] = "Créer une nouvelle archive à télécharger.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['edit']['0'] = "Modifier l'archive";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['edit']['1'] = "Modifie l'archive dont l'ID est %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['copy']['0'] = "Copier l'archive";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['copy']['1'] = "Copie l'archive dont l'ID est %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['delete']['0'] = "Supprimer l'archive";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['delete']['1'] = "Supprime l'archive dont l'ID est %s.";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['show']['0'] = "Afficher les détails";
$GLOBALS['TL_LANG']['tl_downloadarchiv']['show']['1'] = "Affiche les détails de l'archive dont l'ID est %s.";
 
?>
